name: predikce_env
channels:
  - conda-forge
dependencies:
  - python=3.10.18
  - numpy=2.2.4
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - matplotlib=3.10.0
  - joblib=1.2.0
  - streamlit=1.42.0
  - openpyxl=3.1.5
  - jupyter=1.1.1
  - ipykernel=6.29.5
